---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploying Nginx to ECS Fargate using AWS SAM

Resources:
  ECSServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: ecs.amazonaws.com
      Description: Role to enable Amazon ECS to manage your cluster. 
  NginxTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: nginx-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: nginx-container
          Image: "public.ecr.aws/nginx/nginx:stable"
          PortMappings:
            - ContainerPort: 80
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ecs-execution-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                Resource: "*"

  ECSCluster:
    Type: AWS::ECS::Cluster
    DependsOn:
      - ECSServiceLinkedRole

  # ECSService:
  #   Type: AWS::ECS::Service
  #   DependsOn: ECSCluster
  #   Properties:
  #     Cluster: !Ref ECSCluster
  #     DesiredCount: 1
  #     TaskDefinition: !Ref NginxTaskDefinition
  #     LaunchType: FARGATE
  #     NetworkConfiguration:
  #       AwsvpcConfiguration:
  #         AssignPublicIp: ENABLED

# Outputs:
#   ServiceEndpoint:
#     Description: URL of the Nginx service
#     Value: !Sub "http://${ECSService.LoadBalancer.DNSName}"