---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Sample SAM Template Main
Parameters:
  Name:
    Description: Name of App
    Type: String
    Default: rex
  EnvironmentType:
    Description: Name of Environment Type. Example - prod, test
    Type: String
    Default: test
  Owner:
    Description: An owner's login or team
    Type: String
    AllowedPattern: ".+"
    Default: Platform
  ECCFSubnets:
    Type: "AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>"
    Default: "/CNS/resources/subnets/eccf/primary"
  VpcId:
    Description: VpcId
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CNS/resources/vpc_id
  AppPort:
    Description: Port no. for the app
    Type: Number
    Default: 80
Resources:   # Add Resource here
  # ECSServiceLinkedRole:
  #   Type: AWS::IAM::ServiceLinkedRole
  #   Properties:
  #     AWSServiceName: ecs.amazonaws.com
  #     Description: Role to enable Amazon ECS to manage your cluster.     
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterName: rex-develop-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: EnvironmentType
          Value: !Ref EnvironmentType
        - Key: Name
          Value: !Ref Name

  ClusterSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Name}/${EnvironmentType}/ecs_cluster_name
      Type: String
      Value: !Ref Cluster
      Tags:
        Owner: !Ref Owner
        EnvironmentType: !Ref EnvironmentType
        Name: !Ref Name
